import { spawnSync } from "node:child_process";
import { ROUTES } from "../src/catalog-authority.ts";
import { discoveryInputExample } from "../src/discovery.ts";
function arg(name){const i=process.argv.indexOf(name);return i>=0?process.argv[i+1]:undefined}
const origin=(arg("--origin")??"").replace(/\/$/,"");const network=arg("--network")??"";const payee=(arg("--payee")??"").toLowerCase();
const ASSETS=Object.freeze({"eip155:8453":"0x833589fcd6edb6e08f4c7c32d4f71b54bda02913","eip155:84532":"0x036cbd53842c5426634e7929541ec2318f3dcf7e"});
if(!/^https:\/\//.test(origin))throw new Error("ORIGIN_HTTPS_REQUIRED");if(!Object.hasOwn(ASSETS,network))throw new Error("NETWORK_NOT_ALLOWLISTED");if(!/^0x[a-f0-9]{40}$/.test(payee))throw new Error("PAYEE_REQUIRED");const expectedAsset=ASSETS[network];
function decodeHeader(value){const normalized=value.trim().replace(/-/g,"+").replace(/_/g,"/");const padded=normalized.padEnd(Math.ceil(normalized.length/4)*4,"=");return JSON.parse(Buffer.from(padded,"base64").toString("utf8"));}
function curlProbe(url,body){const bin=process.platform==="win32"?"curl.exe":"curl";const args=["-sS","--max-time","20","-D","-","-o",process.platform==="win32"?"NUL":"/dev/null","-X","POST",url,"-H","content-type: application/json","--data-binary",body];const r=spawnSync(bin,args,{encoding:"utf8",maxBuffer:2_000_000});if(r.error)throw r.error;if(r.status!==0)throw new Error(`TRANSPORT_INCONCLUSIVE curl_exit=${r.status} ${String(r.stderr).slice(0,300)}`);const blocks=r.stdout.split(/\r?\n\r?\n/).filter(Boolean);const headerBlock=[...blocks].reverse().find(b=>/^HTTP\//m.test(b));if(!headerBlock)throw new Error("TRANSPORT_INCONCLUSIVE no_http_headers");const statusMatch=/^HTTP\/\S+\s+(\d+)/mi.exec(headerBlock);const status=statusMatch?Number(statusMatch[1]):0;const headers={};for(const line of headerBlock.split(/\r?\n/).slice(1)){const i=line.indexOf(":");if(i>0)headers[line.slice(0,i).trim().toLowerCase()]=line.slice(i+1).trim();}return{status,headers};}
for(const route of ROUTES){const body=JSON.stringify(discoveryInputExample(route.schema));const res=curlProbe(`${origin}${route.path}`,body);if(res.status!==402)throw new Error(`ROUTE_RED ${route.path} status=${res.status}`);const header=res.headers["payment-required"];if(!header)throw new Error(`ROUTE_RED ${route.path} missing_payment_required`);let pr;try{pr=decodeHeader(header)}catch{throw new Error(`ROUTE_RED ${route.path} invalid_payment_required`)}if(pr?.x402Version!==2)throw new Error(`ROUTE_RED ${route.path} x402_version`);const resource=new URL(pr?.resource?.url??"").toString();if(resource!==new URL(`${origin}${route.path}`).toString())throw new Error(`ROUTE_RED ${route.path} resource_mismatch`);const accepts=Array.isArray(pr?.accepts)?pr.accepts:[];const expectedAmount=String(Math.round(route.priceUsd*1_000_000));const option=accepts.find(a=>a?.scheme==="exact"&&a?.network===network&&String(a?.payTo??"").toLowerCase()===payee&&String(a?.asset??"").toLowerCase()===expectedAsset&&String(a?.amount??"")===expectedAmount);if(!option)throw new Error(`ROUTE_RED ${route.path} payment_terms_or_asset`);if(!pr?.extensions?.bazaar)throw new Error(`ROUTE_RED ${route.path} bazaar_missing`);console.log(`RUNTIME_402_BAZAAR_GREEN ${route.path}`);}console.log(`RUNTIME_ALL_GREEN=${ROUTES.length}`);
