export type RouteFamily = "agentutility" | "stableenrich-safe" | "claw402-lite" | "x402-infra" | "agent-security";
export interface RouteSpec { id:string; method:"POST"; path:string; engine:string; priceUsd:number; description:string; schema:Record<string,unknown>; outputExample:Record<string,unknown>; priority:"launch"|"alias"; family:RouteFamily; }
const str=(name:string)=>({type:"object",properties:{[name]:{type:"string"}},required:[name],additionalProperties:false});
export const ROUTES: RouteSpec[] = [
{id:"fx-rate",method:"POST",path:"/v1/fx/rate",engine:"fx",priceUsd:0.01,description:"Latest reference FX rate between two ISO currencies.",schema:{type:"object",properties:{base:{type:"string",example:"USD"},quote:{type:"string",example:"EUR"}},required:["base","quote"],additionalProperties:false},outputExample:{base:"USD",quote:"EUR",rate:0.91},priority:"launch",family:"agentutility"},
{id:"exchange-rates",method:"POST",path:"/v1/exchange-rates",engine:"fx",priceUsd:0.01,description:"Agent-friendly latest currency exchange rate.",schema:{type:"object",properties:{base:{type:"string",default:"USD",example:"USD"},quote:{type:"string",default:"EUR",example:"EUR"}},required:["base","quote"],additionalProperties:false},outputExample:{base:"USD",quote:"EUR",rate:0.91},priority:"launch",family:"agentutility"},
{id:"fx-convert",method:"POST",path:"/v1/fx/convert",engine:"fx",priceUsd:0.01,description:"Convert an amount using latest reference FX rate.",schema:{type:"object",properties:{base:{type:"string",default:"USD",example:"USD"},quote:{type:"string",default:"EUR",example:"EUR"},amount:{type:"number",default:100,example:100}},required:["base","quote","amount"],additionalProperties:false},outputExample:{amount:100,converted:91},priority:"launch",family:"agentutility"},
{id:"currency-convert",method:"POST",path:"/v1/currency-convert",engine:"fx",priceUsd:0.01,description:"Alias for deterministic currency conversion.",schema:{type:"object",properties:{base:{type:"string",default:"USD",example:"USD"},quote:{type:"string",default:"EUR",example:"EUR"},amount:{type:"number",default:100,example:100}},required:["base","quote","amount"],additionalProperties:false},outputExample:{amount:100,converted:91},priority:"alias",family:"agentutility"},
{id:"earthquakes-recent",method:"POST",path:"/v1/earthquakes/recent",engine:"earthquakes",priceUsd:0.01,description:"Recent earthquakes from the USGS daily feed with optional magnitude filter.",schema:{type:"object",properties:{min_magnitude:{type:"number",default:0},limit:{type:"integer",default:25}},additionalProperties:false},outputExample:{count:2,earthquakes:[]},priority:"launch",family:"agentutility"},
{id:"seismic-recent",method:"POST",path:"/v1/seismic/recent",engine:"earthquakes",priceUsd:0.01,description:"Alias for recent USGS seismic events.",schema:{type:"object",properties:{min_magnitude:{type:"number"},limit:{type:"integer"}},additionalProperties:false},outputExample:{count:2,earthquakes:[]},priority:"alias",family:"agentutility"},
{id:"cron-validate",method:"POST",path:"/v1/cron/validate",engine:"cron",priceUsd:0.01,description:"Validate a standard 5-field cron expression.",schema:str("expression"),outputExample:{valid:true},priority:"launch",family:"agentutility"},
{id:"cron-explain",method:"POST",path:"/v1/cron/explain",engine:"cron",priceUsd:0.01,description:"Validate and explain a standard 5-field cron expression.",schema:str("expression"),outputExample:{summary:"every minute; hour=9"},priority:"launch",family:"agentutility"},
{id:"cron-parse",method:"POST",path:"/v1/cron-parse",engine:"cron",priceUsd:0.01,description:"Agent-friendly alias for cron parsing and explanation.",schema:str("expression"),outputExample:{summary:"every minute"},priority:"alias",family:"agentutility"},
{id:"json-inspect",method:"POST",path:"/v1/json/inspect",engine:"json",priceUsd:0.01,description:"Inspect JSON structure and return deterministic canonical JSON.",schema:{type:"object",properties:{value:{}},required:["value"],additionalProperties:false},outputExample:{type:"object",keys:["a"]},priority:"launch",family:"agentutility"},
{id:"json-validate",method:"POST",path:"/v1/json/validate",engine:"json",priceUsd:0.01,description:"Alias for JSON validation and deterministic canonicalization.",schema:{type:"object",properties:{value:{}},required:["value"],additionalProperties:false},outputExample:{type:"object"},priority:"alias",family:"agentutility"},
{id:"hash-sha256",method:"POST",path:"/v1/hash/sha256",engine:"hash",priceUsd:0.01,description:"Compute SHA-256 digest of UTF-8 text.",schema:{type:"object",properties:{text:{type:"string",maxLength:262144}},required:["text"],additionalProperties:false},outputExample:{algorithm:"sha256",digest:"..."},priority:"launch",family:"agentutility"},
{id:"text-fingerprint",method:"POST",path:"/v1/text/fingerprint",engine:"hash",priceUsd:0.01,description:"Alias for stable SHA-256 text fingerprinting.",schema:{type:"object",properties:{text:{type:"string",maxLength:262144}},required:["text"],additionalProperties:false},outputExample:{digest:"..."},priority:"alias",family:"agentutility"},
{id:"domain-normalize",method:"POST",path:"/v1/domain/normalize",engine:"domain-normalize",priceUsd:0.01,description:"Normalize and validate a public DNS domain name.",schema:str("domain"),outputExample:{domain:"example.com"},priority:"launch",family:"stableenrich-safe"},
{id:"url-normalize",method:"POST",path:"/v1/url/normalize",engine:"url-normalize",priceUsd:0.01,description:"Normalize a public HTTP/HTTPS URL and reject local/private targets.",schema:str("url"),outputExample:{url:"https://example.com/",hostname:"example.com"},priority:"launch",family:"stableenrich-safe"},
{id:"email-preflight",method:"POST",path:"/v1/email/preflight",engine:"email-preflight",priceUsd:0.02,description:"Email syntax plus MX preflight; no mailbox probing and no personal-data enrichment.",schema:str("email"),outputExample:{syntax_valid:true,has_mx:true},priority:"launch",family:"stableenrich-safe"},
{id:"email-domain-check",method:"POST",path:"/v1/email/domain-check",engine:"email-preflight",priceUsd:0.02,description:"Alias for email-domain MX preflight without sending mail.",schema:str("email"),outputExample:{has_mx:true},priority:"alias",family:"stableenrich-safe"},
{id:"dns-lookup",method:"POST",path:"/v1/domain/dns",engine:"dns",priceUsd:0.01,description:"DNS lookup for a public domain using selected record types.",schema:{type:"object",properties:{domain:{type:"string"},types:{type:"array",items:{type:"string"},maxItems:5}},required:["domain"],additionalProperties:false},outputExample:{answers:{A:[]}},priority:"launch",family:"stableenrich-safe"},
{id:"domain-preflight",method:"POST",path:"/v1/domain/preflight",engine:"preflight",priceUsd:0.02,description:"Composite domain preflight: A, AAAA and MX availability.",schema:str("domain"),outputExample:{has_dns:true,has_mx:true},priority:"launch",family:"stableenrich-safe"},
{id:"agent-preflight",method:"POST",path:"/v1/agent/preflight",engine:"preflight",priceUsd:0.02,description:"One-call preflight for a URL, domain or email using safe read-only checks.",schema:{type:"object",properties:{kind:{type:"string",enum:["url","domain","email"]},value:{type:"string"}},required:["kind","value"],additionalProperties:false},outputExample:{ok:true},priority:"launch",family:"stableenrich-safe"},
{id:"domain-enrich",method:"POST",path:"/v1/domain/enrich",engine:"domain-enrich",priceUsd:0.02,description:"Public technical domain enrichment: DNS presence, MX, NS, CAA, SPF and DMARC signals; no people data.",schema:str("domain"),outputExample:{domain:"example.com",has_dns:true,has_mx:true,spf_present:true,dmarc_present:true},priority:"launch",family:"stableenrich-safe"},
{id:"domain-mail-security",method:"POST",path:"/v1/domain/mail-security",engine:"domain-enrich",priceUsd:0.02,description:"Technical mail-domain posture from public DNS: MX, SPF and DMARC presence without mailbox probing.",schema:str("domain"),outputExample:{domain:"example.com",has_mx:true,spf_present:true,dmarc_present:true},priority:"launch",family:"stableenrich-safe"},
{id:"email-domain-enrich",method:"POST",path:"/v1/email/domain-enrich",engine:"domain-enrich",priceUsd:0.02,description:"Extract an email domain and return public DNS/MX/SPF/DMARC posture; no person enrichment or SMTP probing.",schema:str("email"),outputExample:{domain:"example.com",has_mx:true,spf_present:true,dmarc_present:true},priority:"alias",family:"stableenrich-safe"},
{id:"gateway-run",method:"POST",path:"/v1/gateway/run",engine:"gateway",priceUsd:0.02,description:"One normalized gateway call to a safe utility by tool id, using the same internal engines as the direct endpoints.",schema:{type:"object",properties:{tool:{type:"string",enum:["exchange-rates","fx-convert","earthquakes-recent","cron-explain","domain-preflight","domain-enrich","email-preflight","dns-lookup","url-normalize","json-inspect","hash-sha256"]},input:{type:"object"}},required:["tool","input"],additionalProperties:false},outputExample:{tool:"cron-explain",result:{}},priority:"launch",family:"claw402-lite"},
{id:"gateway-batch",method:"POST",path:"/v1/gateway/batch",engine:"gateway",priceUsd:0.05,description:"Batch up to five safe utility calls behind one paid gateway request; the batch is atomic on handler errors.",schema:{type:"object",properties:{calls:{type:"array",minItems:1,maxItems:5,items:{type:"object",properties:{tool:{type:"string"},input:{type:"object"}},required:["tool","input"],additionalProperties:false}}},required:["calls"],additionalProperties:false},outputExample:{count:2,results:[]},priority:"launch",family:"claw402-lite"},
{id:"intent-resolve",method:"POST",path:"/v1/intent/resolve",engine:"gateway",priceUsd:0.02,description:"Resolve a bounded agent intent alias and execute it through the existing vetted gateway and canonical engine.",schema:{type:"object",properties:{intent:{type:"string",enum:["exchange rate","currency conversion","recent earthquakes","explain cron","domain preflight","domain enrichment","mail security","email validation","dns lookup","normalize url","inspect json","json validation","sha256","text fingerprint"]},input:{type:"object"}},required:["intent","input"],additionalProperties:false},outputExample:{intent:"json validation",tool:"json-inspect",canonical_route:"/v1/gateway/run",result:{}},priority:"alias",family:"claw402-lite"},
{id:"dependency-gate",method:"POST",path:"/v1/agent/dependency-gate",engine:"dependency-gate",priceUsd:0.015,description:"Pre-install dependency gate for coding agents. Checks up to five exact/default npm or PyPI packages against deps.dev dependency graphs and OSV vulnerability data, returning ALLOW/WARN/BLOCK with evidence before installation.",schema:{type:"object",properties:{packages:{type:"array",minItems:1,maxItems:5,example:[{ecosystem:"npm",name:"hono",version:"4.13.2"}],items:{type:"object",properties:{ecosystem:{type:"string",enum:["npm","pypi"]},name:{type:"string",maxLength:214},version:{type:"string",maxLength:100}},required:["ecosystem","name"],additionalProperties:false}},policy:{type:"object",properties:{block_on_any_direct_vulnerability:{type:"boolean",default:true},fail_on_deprecated:{type:"boolean",default:false},denied_licenses:{type:"array",items:{type:"string"},maxItems:20}},additionalProperties:false}},required:["packages"],additionalProperties:false},outputExample:{decision:"ALLOW",install_allowed:true,package_count:1,packages:[{ecosystem:"npm",name:"hono",resolved_version:"4.13.2",decision:"ALLOW",vulnerability_count:0}],provenance:["deps.dev v3","OSV.dev v1"]},priority:"launch",family:"agent-security"},
{id:"release-gate",method:"POST",path:"/v1/agent/release-gate",engine:"release-gate",priceUsd:0.04,description:"Pre-release gate for coding agents. Scans supplied added diff lines for exposed secrets, public-client secrets, risky deployment/container settings, unpinned GitHub Actions, destructive SQL migrations and dynamic code execution; optionally folds in Dependency Gate without a second payment.",schema:{type:"object",properties:{changed_files:{type:"array",minItems:1,maxItems:40,example:[{path:"src/app.ts",patch:"@@ -1 +1,2 @@\n import { app } from './app'\n+export const ready = true"}],items:{type:"object",properties:{path:{type:"string",maxLength:240},patch:{type:"string",maxLength:32000}},required:["path","patch"],additionalProperties:false}},dependencies:{type:"array",maxItems:5,items:{type:"object",properties:{ecosystem:{type:"string",enum:["npm","pypi"]},name:{type:"string",maxLength:214},version:{type:"string",maxLength:100}},required:["ecosystem","name"],additionalProperties:false}},dependency_policy:{type:"object"},policy:{type:"object",properties:{fail_on_warn:{type:"boolean",default:false}},additionalProperties:false}},required:["changed_files"],additionalProperties:false},outputExample:{ship:true,grade:"PASS",changed_file_count:1,finding_count:0,findings:[],checks:["secret-patterns","deployment-config","destructive-migrations"]},priority:"launch",family:"agent-security"},
{id:"x402-health",method:"POST",path:"/v1/x402/health",engine:"x402-health",priceUsd:0.01,description:"Bounded x402 endpoint health and protocol check: latency, unpaid 402 challenge, v2 fields, exact resource binding, Base USDC and Bazaar metadata. No payment is sent to the inspected target.",schema:{type:"object",properties:{url:{type:"string",format:"uri",example:"https://x402.payai.network/api/base/paid-content"},method:{type:"string",enum:["GET","POST"],default:"GET",example:"GET"}},required:["url"],additionalProperties:false},outputExample:{reachable:true,status:402,latency_ms:120,x402_version:2,protocol_valid:true,resource_matches_target:true,base_mainnet:true,canonical_base_usdc:true,bazaar_declared:false},priority:"launch",family:"x402-infra"}
];
export const ROUTE_BY_KEY=new Map(ROUTES.map(r=>[`${r.method} ${r.path}`,r]));
export const ROUTE_BY_PATH=new Map(ROUTES.map(r=>[r.path,r]));
