import { cleanDomain, normalizeEmail, normalizeUrl, roundMoney, sha256Hex } from "./util.ts";
import type { EngineResponse } from "./types.ts";

const FETCH_TIMEOUT_MS = 7000;
function meta(engine: string, source: string, sourceUrl: string | undefined, ttl: number) { return { engine, source, ...(sourceUrl ? { source_url: sourceUrl } : {}), fetched_at: new Date().toISOString(), cache_ttl_s: ttl }; }
async function cachedJson(url: string, ttlSeconds: number, init: RequestInit = {}): Promise<unknown> { const cache = await caches.open("x402-canary-upstream-v1"); const request = new Request(url, { method: "GET", ...(init.headers !== undefined ? { headers: init.headers } : {}) }); const hit = await cache.match(request); if (hit) return hit.json(); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS); let response: Response; try { response = await fetch(request, { ...init, signal: controller.signal }); } catch (err) { if (err instanceof DOMException && err.name === "AbortError") throw new Error("upstream_timeout"); throw new Error("upstream_unavailable"); } finally { clearTimeout(timer); } if (!response.ok) throw new Error(`upstream_http_${response.status}`); const body = await response.text(); let parsed: unknown; try { parsed = JSON.parse(body); } catch { throw new Error("upstream_invalid_json"); } await cache.put(request, new Response(body, { headers: { "content-type": "application/json", "cache-control": `public, max-age=${ttlSeconds}` } })); return parsed; }

export async function fxRate(baseInput: string, quoteInput: string): Promise<EngineResponse<{ base: string; quote: string; rate: number; date: string }>> { const base = baseInput.trim().toUpperCase(); const quote = quoteInput.trim().toUpperCase(); if (!/^[A-Z]{3}$/.test(base) || !/^[A-Z]{3}$/.test(quote)) throw new Error("invalid_currency_code"); if (base === quote) return { data: { base, quote, rate: 1, date: new Date().toISOString().slice(0, 10) }, meta: meta("fx-rate", "local_identity", undefined, 86400) }; const url = `https://api.frankfurter.dev/v2/rate/${encodeURIComponent(base)}/${encodeURIComponent(quote)}`; const json = await cachedJson(url, 300) as { date?: string; rate?: number }; if (typeof json.rate !== "number" || !Number.isFinite(json.rate)) throw new Error("rate_not_found"); return { data: { base, quote, rate: roundMoney(json.rate, 10), date: json.date ?? "unknown" }, meta: meta("fx-rate", "Frankfurter v2 institutional reference rates", url, 300) }; }
export async function fxConvert(base: string, quote: string, amountInput: number) { const amount = Number(amountInput); if (!Number.isFinite(amount) || Math.abs(amount) > 1e12) throw new Error("invalid_amount"); const rateResult = await fxRate(base, quote); return { data: { ...rateResult.data, amount, converted: roundMoney(amount * rateResult.data.rate, 8) }, meta: { ...rateResult.meta, engine: "fx-convert" } }; }
export async function earthquakesRecent(minMagnitude = 0, limit = 25): Promise<EngineResponse<{ count: number; earthquakes: Array<Record<string, unknown>> }>> { if (!Number.isFinite(minMagnitude) || minMagnitude < 0 || minMagnitude > 10) throw new Error("invalid_min_magnitude"); if (!Number.isInteger(limit) || limit < 1 || limit > 100) throw new Error("invalid_limit"); const url = "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson"; const json = await cachedJson(url, 60) as { features?: Array<{ id?: string; properties?: Record<string, unknown>; geometry?: { coordinates?: unknown[] } }> }; const rows = (json.features ?? []).filter((f) => typeof f.properties?.mag === "number" && (f.properties.mag as number) >= minMagnitude).slice(0, limit).map((f) => ({ id: f.id, magnitude: f.properties?.mag, place: f.properties?.place, time: f.properties?.time, url: f.properties?.url, coordinates: f.geometry?.coordinates })); return { data: { count: rows.length, earthquakes: rows }, meta: meta("earthquakes-recent", "USGS Earthquake Hazards Program", url, 60) }; }

const CRON_BOUNDS: Array<[number, number]> = [[0,59],[0,23],[1,31],[1,12],[0,7]]; const CRON_NAMES = ["minute", "hour", "day_of_month", "month", "day_of_week"];
function validateCronToken(token: string, min: number, max: number): boolean { for (const segment of token.split(",")) { const [rangePart, stepPart] = segment.split("/"); if (stepPart !== undefined && (!/^\d+$/.test(stepPart) || Number(stepPart) < 1 || Number(stepPart) > max-min+1)) return false; if (rangePart === "*") continue; if (/^\d+$/.test(rangePart!)) { const n = Number(rangePart); if (n < min || n > max) return false; continue; } const match = /^(\d+)-(\d+)$/.exec(rangePart!); if (!match) return false; const a=Number(match[1]), b=Number(match[2]); if (a<min||a>max||b<min||b>max||a>b) return false; } return true; }
export function cronValidate(expression: string) { const exp = expression.trim().replace(/\s+/g," "); const fields=exp.split(" "); if(fields.length!==5) throw new Error("cron_requires_5_fields"); for(let i=0;i<5;i++){const [min,max]=CRON_BOUNDS[i]!; if(!validateCronToken(fields[i]!,min,max)) throw new Error(`invalid_cron_${CRON_NAMES[i]}`);} return { data:{ expression:exp, valid:true, fields:Object.fromEntries(CRON_NAMES.map((n,i)=>[n,fields[i]!]))}, meta:meta("cron-validate","local_deterministic",undefined,86400)}; }
export function cronExplain(expression: string) { const checked=cronValidate(expression); const f=checked.data.fields; const describe=(v:string,label:string)=>v==="*"?`every ${label}`:`${label}=${v}`; return { data:{ expression:checked.data.expression, summary:[describe(f.minute!,"minute"),describe(f.hour!,"hour"),describe(f.day_of_month!,"day-of-month"),describe(f.month!,"month"),describe(f.day_of_week!,"day-of-week")].join("; "), fields:f}, meta:meta("cron-explain","local_deterministic",undefined,86400)}; }
export function domainNormalize(input:string){ return { data:{domain:cleanDomain(input)}, meta:meta("domain-normalize","local_deterministic",undefined,86400)}; }
export function urlNormalize(input:string){ const url=normalizeUrl(input); return { data:{url,hostname:new URL(url).hostname}, meta:meta("url-normalize","local_deterministic",undefined,86400)}; }
async function dnsQueryName(name:string,type:string):Promise<unknown[]>{ const url=`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(name)}&type=${encodeURIComponent(type)}`; const json=await cachedJson(url,60,{headers:{accept:"application/dns-json"}}) as {Answer?:Array<Record<string,unknown>>}; return json.Answer??[]; }
function answerData(rows:unknown[]):string[]{ return rows.map(row=>{ if(!row||typeof row!=="object") return ""; const data=(row as Record<string,unknown>).data; return typeof data==="string"?data.replace(/^"|"$/g,""):""; }).filter(Boolean); }
export async function dnsLookup(domainInput:string,types:string[]=["A","AAAA","MX"]){ const domain=cleanDomain(domainInput); const allowed=new Set(["A","AAAA","MX","TXT","CAA","NS","CNAME"]); const unique=[...new Set(types.map(t=>t.toUpperCase()))]; if(!unique.length||unique.length>5||unique.some(t=>!allowed.has(t))) throw new Error("invalid_dns_types"); const answers:Record<string,unknown[]>={}; for(const type of unique) answers[type]=await dnsQueryName(domain,type); return {data:{domain,answers},meta:meta("dns-lookup","Cloudflare DNS over HTTPS","https://cloudflare-dns.com/dns-query",60)}; }
export async function emailPreflight(input:string){ const normalized=normalizeEmail(input); const dns=await dnsLookup(normalized.domain,["MX"]); const mx=dns.data.answers.MX??[]; return {data:{email:normalized.email,domain:normalized.domain,syntax_valid:true as const,has_mx:mx.length>0,mx},meta:meta("email-preflight","local syntax + Cloudflare DNS over HTTPS","https://cloudflare-dns.com/dns-query",60)}; }
export async function domainPreflight(input:string){ const dns=await dnsLookup(input,["A","AAAA","MX"]); const answers=dns.data.answers; return {data:{domain:dns.data.domain,has_dns:(answers.A?.length??0)+(answers.AAAA?.length??0)>0,has_mx:(answers.MX?.length??0)>0,answers},meta:meta("domain-preflight","Cloudflare DNS over HTTPS","https://cloudflare-dns.com/dns-query",60)}; }
function stableStringify(value:unknown):string{ if(value===null||typeof value!=="object") return JSON.stringify(value); if(Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`; const obj=value as Record<string,unknown>; return `{${Object.keys(obj).sort().map(k=>`${JSON.stringify(k)}:${stableStringify(obj[k])}`).join(",")}}`; }
export function jsonInspect(value:unknown){ const canonical=stableStringify(value); const type=Array.isArray(value)?"array":value===null?"null":typeof value; const data:{type:string;keys?:string[];length?:number;canonical_json:string}={type,canonical_json:canonical}; if(Array.isArray(value)) data.length=value.length; if(value&&typeof value==="object"&&!Array.isArray(value)) data.keys=Object.keys(value as Record<string,unknown>).sort(); return {data,meta:meta("json-inspect","local_deterministic",undefined,86400)}; }
export async function hashSha256(input:string){ if(new TextEncoder().encode(input).byteLength>256*1024) throw new Error("payload_too_large"); return {data:{algorithm:"sha256" as const,digest:await sha256Hex(input),bytes:new TextEncoder().encode(input).byteLength},meta:meta("hash-sha256","local_deterministic",undefined,86400)}; }
export async function domainEnrich(input:string){ const domain=cleanDomain(input); const dns=await dnsLookup(domain,["A","AAAA","MX","NS","CAA"]); const txt=await dnsQueryName(domain,"TXT"); const dmarc=await dnsQueryName(`_dmarc.${domain}`,"TXT"); const spfRecords=answerData(txt).filter(v=>/(^|\s)v=spf1(?:\s|$)/i.test(v)); const dmarcRecords=answerData(dmarc).filter(v=>/^v=dmarc1(?:;|\s|$)/i.test(v)); const answers=dns.data.answers; return {data:{domain,has_dns:(answers.A?.length??0)+(answers.AAAA?.length??0)>0,has_mx:(answers.MX?.length??0)>0,mx:answers.MX??[],nameservers:answers.NS??[],caa:answers.CAA??[],spf_present:spfRecords.length>0,spf_records:spfRecords,dmarc_present:dmarcRecords.length>0,dmarc_records:dmarcRecords},meta:meta("domain-enrich","public DNS via Cloudflare DNS over HTTPS","https://cloudflare-dns.com/dns-query",60)}; }
export async function emailDomainEnrich(input:string){ const normalized=normalizeEmail(input); const enriched=await domainEnrich(normalized.domain); return {data:{email:normalized.email,...enriched.data},meta:{...enriched.meta,engine:"domain-enrich"}}; }

export type GatewayTool = "exchange-rates"|"fx-convert"|"earthquakes-recent"|"cron-explain"|"domain-preflight"|"domain-enrich"|"email-preflight"|"dns-lookup"|"url-normalize"|"json-inspect"|"hash-sha256";
function objectInput(input:unknown):Record<string,unknown>{ if(!input||typeof input!=="object"||Array.isArray(input)) throw new Error("gateway_input_object_required"); return input as Record<string,unknown>; }
export async function gatewayRun(toolInput:string,rawInput:unknown){ const tool=toolInput as GatewayTool; const input=objectInput(rawInput); let result:unknown; switch(tool){ case "exchange-rates":result=await fxRate(String(input.base??""),String(input.quote??""));break; case "fx-convert":result=await fxConvert(String(input.base??""),String(input.quote??""),Number(input.amount));break; case "earthquakes-recent":result=await earthquakesRecent(input.min_magnitude===undefined?0:Number(input.min_magnitude),input.limit===undefined?25:Number(input.limit));break; case "cron-explain":result=cronExplain(String(input.expression??""));break; case "domain-preflight":result=await domainPreflight(String(input.domain??""));break; case "domain-enrich":result=await domainEnrich(String(input.domain??""));break; case "email-preflight":result=await emailPreflight(String(input.email??""));break; case "dns-lookup":result=await dnsLookup(String(input.domain??""),Array.isArray(input.types)?input.types.map(String):["A","AAAA","MX"]);break; case "url-normalize":result=urlNormalize(String(input.url??""));break; case "json-inspect":result=jsonInspect(input.value);break; case "hash-sha256":result=await hashSha256(String(input.text??""));break; default:throw new Error("unsupported_gateway_tool"); } return {data:{tool,result},meta:meta("gateway","internal_vetted_engines",undefined,0)}; }
export async function gatewayBatch(callsInput:unknown){ if(!Array.isArray(callsInput)||callsInput.length<1||callsInput.length>5) throw new Error("gateway_batch_requires_1_to_5_calls"); const results:unknown[]=[]; for(const raw of callsInput){ const call=objectInput(raw); results.push((await gatewayRun(String(call.tool??""),call.input)).data);} return {data:{count:results.length,results},meta:meta("gateway","internal_vetted_engines",undefined,0)}; }
export async function agentPreflight(kind:string,value:string):Promise<EngineResponse<Record<string,unknown>>>{ if(kind==="email") return emailPreflight(value) as Promise<EngineResponse<Record<string,unknown>>>; if(kind==="domain") return domainPreflight(value) as Promise<EngineResponse<Record<string,unknown>>>; if(kind==="url") return urlNormalize(value) as EngineResponse<Record<string,unknown>>; throw new Error("invalid_preflight_kind"); }