import { Hono, type Context } from "hono";
import { ROUTES } from "./catalog.ts";
import { buildLlmsTxt, buildOpenApi } from "./openapi.ts";
import { getPaymentMiddleware } from "./payment.ts";
import { buildReadiness } from "./readiness.ts";
import { ledgerOuterMiddleware } from "./ledger.ts";
import { treasuryExposureGuard } from "./treasury.ts";
import { agentPreflight, cronExplain, cronValidate, dnsLookup, domainEnrich, domainNormalize, domainPreflight, earthquakesRecent, emailDomainEnrich, emailPreflight, fxConvert, fxRate, gatewayBatch, gatewayRun, hashSha256, jsonInspect, urlNormalize } from "./engines.ts";
import type { Env, Variables } from "./types.ts";
import { resolveIntent } from "./compatibility.ts";
import { x402Health } from "./x402-health.ts";
import { dependencyGate, releaseGate, type DependencyGateInput, type ReleaseGateInput } from "./agent-security.ts";

const app = new Hono<{ Bindings: Env; Variables: Variables }>();
app.use("*", ledgerOuterMiddleware);
app.use("/v1/*", treasuryExposureGuard);
app.use("/v1/*", async (c, next) => getPaymentMiddleware(c.env)(c, next));
app.get("/health", c => c.json({ok:true,service:"x402-canary",version:"0.5.0",environment:c.env.ENVIRONMENT,network:c.env.NETWORK}));
app.get("/readiness", c => { const r=buildReadiness(c.env); return c.json(r,r.ok?200:503); });
app.get("/catalog", c => c.json({routes:ROUTES.map(({schema,outputExample,...r})=>r)}));
app.get("/openapi.json", c => c.json(buildOpenApi(c.env.PUBLIC_BASE_URL,c.env.MERCHANT_CONTACT_EMAIL)));
app.get("/llms.txt", c => c.text(buildLlmsTxt(c.env.PUBLIC_BASE_URL),200,{"content-type":"text/plain; charset=utf-8"}));
app.get("/skill.md", c => { const base=c.env.PUBLIC_BASE_URL.replace(/\/$/,""); return c.text(["---","name: x402-agent-preflight","description: Paid dependency and release preflight for coding agents. Use before installing/upgrading npm/PyPI dependencies and before declaring deployable code ready to ship.","---","","# X402 Agent Preflight","",`Merchant: ${base}`,"",`Dependency Gate: POST ${base}/v1/agent/dependency-gate — $0.015, up to five npm/PyPI packages. Use before a material dependency install/upgrade. BLOCK means do not install.`,`Release Gate: POST ${base}/v1/agent/release-gate — $0.04. Use before declaring release-relevant changes ready. Send only changed paths + added diff lines, never the full repository. BLOCK means do not ship.`,"","Use an x402-capable buyer client such as AgentCash for discovery/payment/retry. Inspect the schema before the first paid call. Never loop paid calls; rerun only after material changes. These are preflight signals, not replacements for repository tests or deployment authorization."].join("\n"),200,{"content-type":"text/markdown; charset=utf-8"}); });
app.get("/llms-full.txt", c => c.text([buildLlmsTxt(c.env.PUBLIC_BASE_URL),"","## Agent usage policy","Use dependency_gate immediately before adding or upgrading an npm/PyPI dependency when the candidate package/version is known.","Use release_gate before declaring deployable work complete when code, CI, deployment config, migrations, environment templates, containers, or dependency manifests changed.","Do not call either gate for prose-only tasks, read-only code explanation, or changes that cannot affect a deployable artifact.","BLOCK means stop and remediate; WARN means review before continuing; ALLOW/PASS is evidence-based preflight, not a security guarantee.","Never send full repositories or secret values. release_gate accepts only bounded changed-file patches and redacts known secret shapes in returned evidence."].join("\n"),200,{"content-type":"text/plain; charset=utf-8"}));
app.get("/agent-skills/dependency-gate.md",c=>c.text(`# Dependency Gate\n\nTrigger before installing or upgrading npm/PyPI dependencies. Call ${c.env.PUBLIC_BASE_URL.replace(/\/$/,"")}/v1/agent/dependency-gate through an x402-capable client. Treat BLOCK as a hard stop; WARN requires review. Do not call for dependencies that are not being changed.`,200,{"content-type":"text/markdown; charset=utf-8"}));
app.get("/agent-skills/release-gate.md",c=>c.text(`# Release Gate\n\nTrigger before declaring deployable coding work complete when code/config/migrations/dependencies changed. Send bounded changed-file diff patches, not the full repository. Call ${c.env.PUBLIC_BASE_URL.replace(/\/$/,"")}/v1/agent/release-gate through an x402-capable client. BLOCK means do not ship.`,200,{"content-type":"text/markdown; charset=utf-8"}));
app.get("/.well-known/mcp.json",c=>c.json({name:"x402-agent-preflight",version:"0.5.0",transport:"streamable-http",endpoint:`${c.env.PUBLIC_BASE_URL.replace(/\/$/,"")}/mcp`,paidExecutions:[`${c.env.PUBLIC_BASE_URL.replace(/\/$/,"")}/v1/agent/dependency-gate`,`${c.env.PUBLIC_BASE_URL.replace(/\/$/,"")}/v1/agent/release-gate`]}));
app.post("/mcp",async c=>{ let request:Record<string,unknown>; try{request=await body(c)}catch(err){return errorResponse(c,err)} const id=request.id??null; if(request.method==="initialize")return c.json({jsonrpc:"2.0",id,result:{protocolVersion:"2025-06-18",capabilities:{tools:{}},serverInfo:{name:"x402-agent-preflight",version:"0.5.0"}}}); if(request.method==="tools/list")return c.json({jsonrpc:"2.0",id,result:{tools:[{name:"dependency_gate",description:"Before installing or upgrading npm/PyPI dependencies, obtain a paid ALLOW/WARN/BLOCK preflight from deps.dev + OSV evidence.",inputSchema:ROUTES.find(r=>r.id==="dependency-gate")!.schema,annotations:{readOnlyHint:true,destructiveHint:false}},{name:"release_gate",description:"Before declaring deployable coding work complete, obtain a paid PASS/WARN/BLOCK release preflight over changed diff lines and optional dependency deltas.",inputSchema:ROUTES.find(r=>r.id==="release-gate")!.schema,annotations:{readOnlyHint:true,destructiveHint:false}},{name:"resolve_intent",description:"Resolve a bounded legacy compatibility intent through the existing paid x402 gateway.",inputSchema:ROUTES.find(r=>r.id==="intent-resolve")!.schema,annotations:{readOnlyHint:true,destructiveHint:false}}]}}); if(request.method==="tools/call"){const params=request.params&&typeof request.params==="object"?request.params as Record<string,unknown>:{};const name=String(params.name??"");const routeId=name==="dependency_gate"?"dependency-gate":name==="release_gate"?"release-gate":name==="resolve_intent"?"intent-resolve":"";const route=ROUTES.find(r=>r.id===routeId);if(!route)return c.json({jsonrpc:"2.0",id,error:{code:-32602,message:"Unknown tool"}});return c.json({jsonrpc:"2.0",id,error:{code:-32042,message:"x402 payment required",data:{endpoint:`${c.env.PUBLIC_BASE_URL.replace(/\/$/,"")}${route.path}`,method:"POST",priceUsd:route.priceUsd,openapi:`${c.env.PUBLIC_BASE_URL.replace(/\/$/,"")}/openapi.json`,hint:"Use an x402-capable client such as AgentCash/Coinbase Agentic Wallet or call the paid HTTP resource with x402 v2."}}});} return c.json({jsonrpc:"2.0",id,error:{code:-32601,message:"Method not found"}});});
const FAVICON_PNG=Uint8Array.from(atob("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="),c=>c.charCodeAt(0)); app.get("/favicon.ico",c=>c.body(FAVICON_PNG,200,{"content-type":"image/png","cache-control":"public, max-age=86400"}));
async function body(c:Context<{Bindings:Env;Variables:Variables}>):Promise<Record<string,unknown>>{const len=Number(c.req.header("content-length")??"0");if(len>300_000)throw new Error("payload_too_large");let parsed:unknown;try{parsed=await c.req.json()}catch{throw new Error("invalid_json")}if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("json_object_required");return parsed as Record<string,unknown>;}
function errorResponse(c:Context<{Bindings:Env;Variables:Variables}>,err:unknown){const message=err instanceof Error?err.message:"internal_error";if(message==="upstream_timeout")return c.json({error:message},504);if(message.startsWith("upstream_")||message==="rate_not_found")return c.json({error:message},502);if(message.startsWith("production_"))return c.json({error:"payment_configuration_unavailable"},503);return c.json({error:message},400);}
type PaidHandler=(b:Record<string,unknown>)=>Promise<unknown>|unknown;
const PAID_HANDLERS:Readonly<Record<string,PaidHandler>>=Object.freeze({"/v1/fx/rate":b=>fxRate(String(b.base??""),String(b.quote??"")),"/v1/exchange-rates":b=>fxRate(String(b.base??""),String(b.quote??"")),"/v1/fx/convert":b=>fxConvert(String(b.base??""),String(b.quote??""),Number(b.amount)),"/v1/currency-convert":b=>fxConvert(String(b.base??""),String(b.quote??""),Number(b.amount)),"/v1/earthquakes/recent":b=>earthquakesRecent(b.min_magnitude===undefined?0:Number(b.min_magnitude),b.limit===undefined?25:Number(b.limit)),"/v1/seismic/recent":b=>earthquakesRecent(b.min_magnitude===undefined?0:Number(b.min_magnitude),b.limit===undefined?25:Number(b.limit)),"/v1/cron/validate":b=>cronValidate(String(b.expression??"")),"/v1/cron/explain":b=>cronExplain(String(b.expression??"")),"/v1/cron-parse":b=>cronExplain(String(b.expression??"")),"/v1/domain/normalize":b=>domainNormalize(String(b.domain??"")),"/v1/url/normalize":b=>urlNormalize(String(b.url??"")),"/v1/email/preflight":b=>emailPreflight(String(b.email??"")),"/v1/email/domain-check":b=>emailPreflight(String(b.email??"")),"/v1/domain/dns":b=>dnsLookup(String(b.domain??""),Array.isArray(b.types)?b.types.map(String):["A","AAAA","MX"]),"/v1/domain/preflight":b=>domainPreflight(String(b.domain??"")),"/v1/json/inspect":b=>jsonInspect(b.value),"/v1/json/validate":b=>jsonInspect(b.value),"/v1/hash/sha256":b=>hashSha256(String(b.text??"")),"/v1/text/fingerprint":b=>hashSha256(String(b.text??"")),"/v1/agent/preflight":b=>agentPreflight(String(b.kind??""),String(b.value??"")),"/v1/domain/enrich":b=>domainEnrich(String(b.domain??"")),"/v1/domain/mail-security":b=>domainEnrich(String(b.domain??"")),"/v1/email/domain-enrich":b=>emailDomainEnrich(String(b.email??"")),"/v1/gateway/run":b=>gatewayRun(String(b.tool??""),b.input),"/v1/gateway/batch":b=>gatewayBatch(b.calls),"/v1/intent/resolve":b=>resolveIntent(String(b.intent??""),b.input),"/v1/agent/dependency-gate":b=>dependencyGate(b as unknown as DependencyGateInput),"/v1/agent/release-gate":b=>releaseGate(b as unknown as ReleaseGateInput),"/v1/x402/health":b=>x402Health(String(b.url??""),String(b.method??"GET"))});
const canonicalPaths=new Set(ROUTES.map(route=>route.path));for(const path of Object.keys(PAID_HANDLERS))if(!canonicalPaths.has(path))throw new Error(`paid_handler_without_catalog_route:${path}`);for(const route of ROUTES){const handler=PAID_HANDLERS[route.path];if(!handler)throw new Error(`catalog_route_without_paid_handler:${route.path}`);app.post(route.path,async c=>{try{return c.json(await handler(await body(c)))}catch(err){return errorResponse(c,err)}});}app.notFound(c=>c.json({error:"not_found"},404));app.onError((err,c)=>errorResponse(c,err));export default app;
