import { ROUTES } from "./catalog-authority.ts";
import { formatUsdAmount } from "./pricing.ts";

export function buildOpenApi(baseUrl: string, contactEmail?: string) {
  const paths: Record<string, unknown> = {};
  for (const route of ROUTES) {
    paths[route.path] = { post: { operationId: route.id, summary: route.description, description: route.description, tags: [route.family, route.engine], "x-family": route.family, "x-payment-info": { protocols: [{ x402: {} }], price: { mode: "fixed", currency: "USD", amount: formatUsdAmount(route.priceUsd) } }, requestBody: { required: true, content: { "application/json": { schema: route.schema } } }, responses: { "200": { description: "Successful response", content: { "application/json": { schema: { type: "object", properties: { data: {}, meta: { type: "object" } }, required: ["data","meta"] }, example: { data: route.outputExample, meta: { engine: route.engine } } } } }, "400": { description: "Invalid input" }, "402": { description: "Payment Required" }, "502": { description: "Upstream unavailable" }, "504": { description: "Upstream timeout" } } } };
  }
  return { openapi: "3.1.0", info: { title: "Coding Agent Context APIs — npm docs, upgrade diff, browser snapshot", version: "0.5.0", description: "Pay-per-call external context for coding agents. Exact npm TypeScript API docs and package metadata, npm version upgrade/breaking-change diff, and real JavaScript-rendered browser snapshots. Also includes deterministic dependency/release preflight and legacy read-only utilities.", "x-guidance": "AgentCash/Claude Code/Codex/Gemini CLI discovery guidance: search for 'npm docs', 'TypeScript API', 'package documentation', 'npm package signature', 'npm upgrade', 'breaking changes', 'migration diff', 'browser snapshot', 'rendered web page', 'JavaScript page', or 'accessibility tree'. Use /v1/agent/npm-symbol-context when exact current npm signatures or package metadata are needed and local installed docs/types are absent or stale. Use /v1/agent/npm-api-diff before a concrete npm upgrade when migration/breaking-change risk is unknown. Use /v1/agent/browser-context when the answer depends on what a public HTTPS page actually renders after JavaScript. Prefer free local evidence when sufficient; buy external context only when current external state materially changes the answer. Paid routes challenge with x402 before body validation and every paid route declares Bazaar metadata. No PII/social/trading/write actions.", ...(contactEmail ? { contact: { email: contactEmail } } : {}) }, servers: [{ url: baseUrl }], paths };
}

export function buildLlmsTxt(baseUrl: string): string {
  const base = baseUrl.replace(/\/$/, "");
  return ["# Coding Agent Context APIs", "", "Pay-per-call fresh external context for coding agents plus preserved preflight and read-only canary utilities.", `OpenAPI: ${base}/openapi.json`, `Catalog: ${base}/catalog`, "Payment: x402 on Base; testnet uses Base Sepolia.", "AgentCash search terms: npm docs; TypeScript API; package documentation; npm package signature; npm upgrade; breaking changes; migration diff; browser snapshot; rendered web page; JavaScript page; accessibility tree.", "Primary context pricing: NPM Symbol Context $0.015; NPM API Diff $0.025; Browser Context $0.03. Dependency Gate remains $0.015 and Release Gate $0.04.", `NPM Symbol Context: ${base}/v1/agent/npm-symbol-context`, `NPM API Diff: ${base}/v1/agent/npm-api-diff`, `Browser Context: ${base}/v1/agent/browser-context`, `Dependency Gate: ${base}/v1/agent/dependency-gate`, `Release Gate: ${base}/v1/agent/release-gate`, `Full agent guidance: ${base}/llms-full.txt`, `x402 health: ${base}/v1/x402/health`, "Use paid external context only when local evidence cannot answer the question reliably. No account, subscription, PII enrichment, trading execution, or write actions."].join("\n");
}
