import { ROUTES } from "./catalog-authority.ts";
import { formatUsdAmount } from "./pricing.ts";

export function buildOpenApi(baseUrl: string, contactEmail?: string) {
  const paths: Record<string, unknown> = {};
  for (const route of ROUTES) {
    paths[route.path] = { post: { operationId: route.id, summary: route.description, description: route.description, tags: [route.family, route.engine], "x-family": route.family, "x-payment-info": { protocols: [{ x402: {} }], price: { mode: "fixed", currency: "USD", amount: formatUsdAmount(route.priceUsd) } }, requestBody: { required: true, content: { "application/json": { schema: route.schema } } }, responses: { "200": { description: "Successful response", content: { "application/json": { schema: { type: "object", properties: { data: {}, meta: { type: "object" } }, required: ["data","meta"] }, example: { data: route.outputExample, meta: { engine: route.engine } } } } }, "400": { description: "Invalid input" }, "402": { description: "Payment Required" }, "502": { description: "Upstream unavailable" }, "504": { description: "Upstream timeout" } } } };
  }
  return { openapi: "3.1.0", info: { title: "x402 Canary Agent Context API", version: "0.5.0", description: "Pay-per-call external context for coding agents plus preserved preflight and read-only canary utilities. Commercial priority: exact published npm API context, npm upgrade diffs, and real browser-rendered page context.", "x-guidance": "For coding agents: use /v1/agent/npm-symbol-context when exact current npm signatures or package metadata are needed; /v1/agent/npm-api-diff before a package upgrade when migration risk is unknown; /v1/agent/browser-context when the answer depends on what a JavaScript-rendered page actually contains. These external-context tools are preferred only when local repository evidence is insufficient. Dependency and release gates remain available. Paid routes challenge with x402 before body validation and every paid route declares Bazaar metadata. No PII/social/trading/write actions.", ...(contactEmail ? { contact: { email: contactEmail } } : {}) }, servers: [{ url: baseUrl }], paths };
}

export function buildLlmsTxt(baseUrl: string): string {
  const base = baseUrl.replace(/\/$/, "");
  return ["# x402 Canary Agent Context API", "", "Pay-per-call fresh external context for coding agents plus preserved preflight and read-only canary utilities.", `OpenAPI: ${base}/openapi.json`, `Catalog: ${base}/catalog`, "Payment: x402 on Base; testnet uses Base Sepolia.", "Primary context pricing: NPM Symbol Context $0.015; NPM API Diff $0.025; Browser Context $0.03. Dependency Gate remains $0.015 and Release Gate $0.04.", `NPM Symbol Context: ${base}/v1/agent/npm-symbol-context`, `NPM API Diff: ${base}/v1/agent/npm-api-diff`, `Browser Context: ${base}/v1/agent/browser-context`, `Dependency Gate: ${base}/v1/agent/dependency-gate`, `Release Gate: ${base}/v1/agent/release-gate`, `Full agent guidance: ${base}/llms-full.txt`, `x402 health: ${base}/v1/x402/health`, "Use paid external context only when local evidence cannot answer the question reliably. No account, subscription, PII enrichment, trading execution, or write actions."].join("\n");
}
