import { decodeBase64Json, isPrivateIpLiteral, normalizeUrl } from "./util.ts";
import type { EngineResponse } from "./types.ts";

const BASE_MAINNET = "eip155:8453";
const BASE_USDC = "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913";
const DNS_TIMEOUT_MS = 3000;
const TARGET_TIMEOUT_MS = 5000;
type ProbeMethod = "GET" | "POST";
type PaymentRequiredV2 = { x402Version?: unknown; resource?: { url?: unknown }; accepts?: Array<Record<string, unknown>>; extensions?: Record<string, unknown>; };
function meta(sourceUrl: string) { return { engine: "x402-health", source: "bounded_unpaid_http_probe", source_url: sourceUrl, fetched_at: new Date().toISOString(), cache_ttl_s: 0 }; }
function publicHttpsUrl(input: string): string { const normalized = normalizeUrl(input); const url = new URL(normalized); if (url.protocol !== "https:") throw new Error("https_required"); if (url.username || url.password) throw new Error("credentials_not_allowed"); if (url.port && url.port !== "443") throw new Error("https_443_required"); if (isPrivateIpLiteral(url.hostname) || /^[0-9.]+$/.test(url.hostname) || url.hostname.includes(":")) throw new Error("hostname_required"); return url.toString(); }
async function fetchJsonWithTimeout(url: string, timeoutMs: number): Promise<any> { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { const res = await fetch(url, { headers: { accept: "application/dns-json" }, signal: controller.signal, redirect: "error" }); if (!res.ok) throw new Error("target_dns_unavailable"); return await res.json(); } catch (err) { if (err instanceof DOMException && err.name === "AbortError") throw new Error("target_dns_timeout"); if (err instanceof Error && err.message.startsWith("target_dns_")) throw err; throw new Error("target_dns_unavailable"); } finally { clearTimeout(timer); } }
async function assertPublicResolution(hostname: string): Promise<void> { if (isPrivateIpLiteral(hostname)) throw new Error("private_or_local_url"); const q = (type: string) => `https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(hostname)}&type=${type}`; const [a, aaaa] = await Promise.all([fetchJsonWithTimeout(q("A"), DNS_TIMEOUT_MS), fetchJsonWithTimeout(q("AAAA"), DNS_TIMEOUT_MS)]); const answers = [...(Array.isArray(a?.Answer) ? a.Answer : []), ...(Array.isArray(aaaa?.Answer) ? aaaa.Answer : [])]; const ips = answers.map((row: any) => typeof row?.data === "string" ? row.data.replace(/^"|"$/g, "") : "").filter((v: string) => v && (/^\d{1,3}(?:\.\d{1,3}){3}$/.test(v) || v.includes(":"))); if (!ips.length) throw new Error("target_dns_unresolved"); if (ips.some((ip: string) => isPrivateIpLiteral(ip))) throw new Error("private_or_local_url"); }
function normalizeComparableUrl(value: unknown): string | null { if (typeof value !== "string") return null; try { return new URL(value).toString(); } catch { return null; } }
export async function x402Health(urlInput: string, methodInput: string = "GET"): Promise<EngineResponse<Record<string, unknown>>> {
  const target = publicHttpsUrl(urlInput); const method = methodInput.trim().toUpperCase() as ProbeMethod; if (method !== "GET" && method !== "POST") throw new Error("invalid_probe_method"); const targetUrl = new URL(target); await assertPublicResolution(targetUrl.hostname);
  const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), TARGET_TIMEOUT_MS); const started = Date.now(); let response: Response;
  const requestInit: RequestInit = { method, headers: method === "POST" ? { "content-type": "application/json", accept: "application/json" } : { accept: "application/json" }, redirect: "manual", signal: controller.signal, ...(method === "POST" ? { body: "{}" } : {}) };
  try { response = await fetch(target, requestInit); }
  catch (err) { const timeout = err instanceof DOMException && err.name === "AbortError"; return { data: { reachable: false, status: null, latency_ms: Date.now() - started, issue: timeout ? "target_timeout" : "target_unavailable", paid_target: false }, meta: meta(target) }; }
  finally { clearTimeout(timer); }
  const latency = Date.now() - started; const header = response.headers.get("payment-required"); const parsed = header ? decodeBase64Json<PaymentRequiredV2>(header) : null; const accepts = Array.isArray(parsed?.accepts) ? parsed!.accepts! : []; const resourceUrl = normalizeComparableUrl(parsed?.resource?.url); const baseOptions = accepts.filter((a) => a.network === BASE_MAINNET); const canonicalUsdcOptions = baseOptions.filter((a) => typeof a.asset === "string" && a.asset.toLowerCase() === BASE_USDC); const summary = accepts.slice(0, 5).map((a) => ({ scheme: a.scheme ?? null, network: a.network ?? null, amount: a.amount ?? null, asset: a.asset ?? null, payTo: a.payTo ?? null }));
  return { data: { reachable: true, status: response.status, latency_ms: latency, redirect_location: response.status >= 300 && response.status < 400 ? response.headers.get("location") : null, x402_version: parsed?.x402Version ?? null, protocol_valid: response.status === 402 && parsed?.x402Version === 2 && accepts.length > 0 && Boolean(resourceUrl), resource_url: resourceUrl, resource_matches_target: resourceUrl === target, accepts: summary, base_mainnet: baseOptions.length > 0, canonical_base_usdc: canonicalUsdcOptions.length > 0, bazaar_declared: Boolean(parsed?.extensions && Object.hasOwn(parsed.extensions, "bazaar")), paid_target: false }, meta: meta(target) };
}